language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - nightly
    - hhvm

matrix:
    include:
        - php: 5.3.3
          dist: precise
          sudo: required
        - php: 5.3
          dist: precise
          sudo: required
        - php: 5.4
          dist: precise
          sudo: required
        - php: 7.0
          env: CS_FIXER=run
    fast_finish: true
    allow_failures:
        - php: 7.3
        - php: nightly
        - php: hhvm

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    # disable TLS for composer because openssl is disabled for PHP 5.3.3 on travis
    # see: https://blog.travis-ci.com/upcoming_ubuntu_11_10_migration/
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- disable-tls true; fi;
    - if [[ $TRAVIS_PHP_VERSION = 5.3.3 ]]; then composer config -g -- secure-http false; fi;

install:
    - composer self-update

before_script:
    - composer install -o --prefer-dist --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/simple-phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;

after_script:
    - php vendor/bin/coveralls -v
